const dietRecipes=[
{cat:'Mëngjes',icon:'🥣',title:'Overnight oats me manaferra',time:'8 min + ftohje',apiSearch:'Breakfast Potatoes',desc:'Tërshërë, kos natyral, manaferra dhe fara chia për një mëngjes të plotë e praktik.',ingredients:['50 g tërshërë','150 g kos natyral','80 ml qumësht','80 g manaferra','1 lugë çaji fara chia'],steps:['Përziej tërshërën, kosin, qumështin dhe farat chia.','Mbuloje dhe lëre në frigorifer gjatë natës.','Shto manaferrat para servirjes.'],note:'Pa sheqer të shtuar; ëmbëlsia vjen nga frutat.'},
{cat:'Drekë',icon:'🥗',title:'Bowl me pulë & quinoa',time:'30 min',apiSearch:'Chicken Quinoa Greek Salad',desc:'Pulë e pjekur, quinoa, perime dhe salcë e lehtë me kos e limon.',ingredients:['120 g gjoks pule','60 g quinoa e thatë','Domate, kastravec dhe sallatë','2 lugë kos natyral','Limon, piper dhe barishte'],steps:['Gatuaj quinoan sipas paketimit.','Piq pulën derisa të jetë plotësisht e gatuar dhe prite në feta.','Mbush tasin me quinoa dhe perime.','Përziej kosin me limon dhe barishte dhe përdore si salcë.'],note:'Vakt i balancuar me proteinë, drithëra dhe shumë perime.'},
{cat:'Darkë',icon:'🐟',title:'Salmon me brokoli & patate',time:'35 min',apiSearch:'Salmon Avocado Salad',desc:'Salmon i pjekur me perime dhe patate, pa skuqje të thellë.',ingredients:['140 g salmon','180 g patate','150 g brokoli','1 lugë çaji vaj ulliri','Limon dhe barishte'],steps:['Prit patatet dhe piqi derisa të zbuten.','Shto salmonin dhe gatuaje plotësisht.','Gatuaj brokolin me avull.','Shërbeji me limon dhe barishte.'],note:'Peshk, perime dhe karbohidrate në një pjatë të thjeshtë.'},
{cat:'Vegjetariane',icon:'🫘',title:'Bowl me qiqra & perime',time:'20 min',apiSearch:'Chickpea Fajitas',desc:'Qiqra, perime shumëngjyrëshe dhe drithëra integrale për një vakt bimor.',ingredients:['120 g qiqra të ziera','60 g bulgur integral','Spec, domate dhe kastravec','Majdanoz','Limon dhe 1 lugë çaji vaj ulliri'],steps:['Gatuaj bulgurin dhe lëre të pushojë.','Shpëlaj qiqrat dhe prit perimet.','Bashkoji të gjitha në një tas.','Shto limon, vaj ulliri dhe majdanoz.'],note:'Burim bimor proteinash dhe fibrash.'},
{cat:'Mëngjes',icon:'🍳',title:'Omëletë me spinaq',time:'12 min',apiSearch:'Spanish Tortilla',desc:'Vezë me spinaq, domate dhe bukë integrale për mëngjes të kripur.',ingredients:['2 vezë','1 grusht spinaq','1 domate e vogël','1 fetë bukë integrale','Piper dhe barishte'],steps:['Zbut spinaqin dhe domaten në tigan.','Rrih vezët dhe shtoji sipër.','Gatuaj derisa veza të jetë plotësisht e gatuar.','Shërbeje me bukë integrale.'],note:'Proteinën e kombinon me perime dhe drithëra integrale.'},
{cat:'Drekë',icon:'🌯',title:'Wrap integral me pulë',time:'18 min',apiSearch:'Chicken Fajita Mac and Cheese',desc:'Wrap integral me pulë, sallatë krokante dhe salcë kosi.',ingredients:['1 tortilla integrale','100 g pulë e gatuar','Sallatë, domate dhe kastravec','2 lugë kos natyral','Limon dhe barishte'],steps:['Ngroh lehtë tortillën.','Prit pulën dhe perimet.','Përziej kosin me limon dhe barishte.','Mbush wrap-in dhe mbështille fort.'],note:'Praktik për drekë dhe i lehtë për t’u përgatitur paraprakisht.'},
{cat:'Darkë',icon:'🍲',title:'Supë me thjerrëza',time:'35 min',apiSearch:'Lentil Soup',desc:'Supë e trashë me thjerrëza, karotë, domate dhe erëza.',ingredients:['80 g thjerrëza','1 karotë','½ qepë','150 g domate të copëtuara','Spinaq dhe erëza'],steps:['Zbut qepën dhe karotën me pak ujë ose vaj.','Shto thjerrëzat, domatet dhe ujë.','Ziej derisa thjerrëzat të jenë të buta.','Shto spinaqin në minutat e fundit.'],note:'Vakt me bishtajore dhe perime, pa nevojë për mish.'},
{cat:'Snack',icon:'🍎',title:'Mollë, kos & arra',time:'5 min',apiSearch:'Fruit and Cream Cheese Breakfast Pastries',desc:'Snack i thjeshtë me fruta, kos natyral dhe arra të copëtuara.',ingredients:['1 mollë','120 g kos natyral','15 g arra të copëtuara','Pak kanellë'],steps:['Prit mollën në kube.','Vendos kosin në tas.','Shto mollën, arrat dhe kanellën.'],note:'Kontrollo alergjitë ndaj arrave; zgjidh kos pa sheqer të shtuar.'},
{cat:'Drekë',icon:'🍚',title:'Oriz integral me ton & perime',time:'25 min',apiSearch:'Tuna and Egg Briks',desc:'Tas i shpejtë me oriz integral, ton dhe perime të freskëta.',ingredients:['70 g oriz integral','100 g ton i konservuar në ujë, i kulluar','Domate, misër dhe kastravec','Limon','Majdanoz'],steps:['Gatuaj orizin dhe lëre të ftohet pak.','Kulloj tonin.','Prit perimet dhe përzieji me orizin.','Shto tonin, limonin dhe majdanozin.'],note:'Kontrollo etiketën për natriumin dhe zgjidh variant më të ulët kur është i disponueshëm.'},
{cat:'Darkë',icon:'🍗',title:'Pulë në furrë me perime',time:'40 min',apiSearch:'Roast Chicken',desc:'Tabaka e vetme me pulë, kungulleshkë, spec dhe karotë.',ingredients:['140 g gjoks pule','1 kungulleshkë e vogël','1 spec','1 karotë','1 lugë çaji vaj ulliri','Erëza dhe limon'],steps:['Ngroh furrën dhe prit perimet.','Vendos pulën dhe perimet në tepsi.','Shto vajin dhe erëzat.','Piq derisa pula të jetë plotësisht e gatuar dhe perimet të zbuten.'],note:'Pjekja ul nevojën për shumë yndyrë gatimi.'},
{cat:'Vegjetariane',icon:'🥑',title:'Toast integral me avokado & vezë',time:'12 min',apiSearch:'Avocado Toast',desc:'Bukë integrale, avokado dhe vezë për një vakt të shpejtë.',ingredients:['2 feta bukë integrale','½ avokado','1 vezë','Domate','Limon dhe piper'],steps:['Pjek lehtë bukën.','Shtyp avokadon me limon.','Gatuaj vezën plotësisht sipas preferencës.','Vendosi mbi bukë dhe shto domate.'],note:'Kombinon drithëra integrale, yndyrë të pangopur dhe proteinë.'},
{cat:'Snack',icon:'🫐',title:'Kos me fruta & fara',time:'4 min',apiSearch:'Summer Pudding',desc:'Kos natyral me fruta të freskëta dhe fara për një snack të shpejtë.',ingredients:['150 g kos natyral','100 g fruta të stinës','1 lugë çaji fara chia ose lini të bluara'],steps:['Vendos kosin në tas.','Laji dhe prit frutat.','Shto frutat dhe farat sipër.'],note:'Zgjidh kos natyral dhe përdor fruta për ëmbëlsi.'}
];
const mealApi='https://www.themealdb.com/api/json/v1/1/search.php?s=';
const dietPhotoCache={};
async function loadDietPhoto(i,img){const r=dietRecipes[i];if(dietPhotoCache[i]){img.src=dietPhotoCache[i];return}try{const res=await fetch(mealApi+encodeURIComponent(r.apiSearch));const data=await res.json();const meal=data.meals&&data.meals[0];if(!meal||!meal.strMealThumb)throw new Error('No meal image');dietPhotoCache[i]=meal.strMealThumb;img.src=meal.strMealThumb}catch(e){img.remove();}}
function dietPhotoTag(i,r,detail=false){return `<img data-meal-photo="${i}" alt="${r.title}" ${detail?'':'loading="lazy"'} decoding="async" onload="this.classList.add('loaded')" onerror="this.remove()">`}
function hydrateDietPhotos(root=document){root.querySelectorAll('img[data-meal-photo]').forEach(img=>loadDietPhoto(Number(img.dataset.mealPhoto),img))}
let dietFilter='Të gjitha';
function dietCard(r,i){return `<article class="diet-card reveal"><div class="diet-photo">${dietPhotoTag(i,r)}<span class="photo-fallback">${r.icon}</span><small>${r.cat}</small></div><div class="diet-meta"><span>${r.cat}</span><span>${r.time}</span></div><h3>${r.title}</h3><p>${r.desc}</p><button onclick="openDietRecipe(${i})">Hape recetën <b>↗</b></button></article>`}
function renderDiet(){const box=document.querySelector('#dietGrid');if(!box)return;box.innerHTML=dietRecipes.map((r,i)=>({r,i})).filter(x=>dietFilter==='Të gjitha'||x.r.cat===dietFilter).map(x=>dietCard(x.r,x.i)).join('');document.querySelectorAll('.diet-filter').forEach(x=>x.classList.toggle('active',x.dataset.f===dietFilter));hydrateDietPhotos(box);initReveal()}
function setDietFilter(f){dietFilter=f;renderDiet()}
function openDiet(){app.classList.add('page-shift');setTimeout(()=>{app.classList.remove('page-shift');app.innerHTML=`<div class="diet-shell"><header class="diet-nav"><a class="brand" onclick="home()"><i>m</i><span>miranda<small>healthy table</small></span></a><nav><button onclick="home()">Beba 6–12 muaj</button><button class="active">Ushqim i shëndetshëm</button></nav></header><main><section class="diet-hero reveal"><div><p class="eyebrow">MIRANDA · HEALTHY TABLE</p><h1>Ha mirë.<br><em>Ndihu lehtë.</em></h1><p>Një hapësirë e veçantë me receta të përditshme të fokusuara te perimet, frutat, drithërat, bishtajoret dhe burimet e ndryshme të proteinës. Jo “dietë urie” — ushqim i balancuar dhe praktik.</p><div class="diet-stats"><span><b>${dietRecipes.length}</b> receta</span><span><b>6</b> kategori</span><span><b>1</b> kuzhinë e thjeshtë</span></div></div><div class="plate-orbit"><div class="plate">🥗</div><span class="orbit o1">🥦</span><span class="orbit o2">🍅</span><span class="orbit o3">🥑</span></div></section><section class="diet-library"><div class="section-head"><div><p class="eyebrow">ZGJIDH SIPAS VAKTIT</p><h2>Biblioteka healthy</h2></div><p>Receta me përbërës dhe përgatitje të qartë, me fotografi reale të ushqimit nga TheMealDB.</p></div><div class="filters diet-filters">${['Të gjitha','Mëngjes','Drekë','Darkë','Vegjetariane','Snack'].map(f=>`<button class="filter diet-filter ${f==='Të gjitha'?'active':''}" data-f="${f}" onclick="setDietFilter('${f}')">${f}</button>`).join('')}</div><div id="dietGrid" class="diet-grid"></div></section><section class="balance-strip"><p class="eyebrow">PARIMI</p><h2>Shumëllojshmëri, jo ekstrem.</h2><p>Syno një model ushqimi me fruta e perime, drithëra, burime të ndryshme proteinash dhe produkte qumështi ose alternativa të fortifikuara, duke kufizuar sheqernat e shtuara, yndyrën e ngopur dhe natriumin.</p></section></main></div>`;scrollTo(0,0);renderDiet();initReveal()},180)}
function openDietRecipe(i){const r=dietRecipes[i];app.innerHTML=`<div class="diet-detail-page"><button class="back" onclick="openDiet()">← Healthy Table</button><div class="diet-detail reveal"><div class="diet-detail-visual meal-photo">${dietPhotoTag(i,r,true)}<span class="photo-fallback">${r.icon}</span><small>${r.cat}</small></div><div><p class="eyebrow">${r.cat} · ${r.time}</p><h1>${r.title}</h1><p class="detail-intro">${r.desc}</p><section class="detail-section"><h3>Përbërësit</h3><ul>${r.ingredients.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="detail-section"><h3>Përgatitja</h3><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol></section><div class="healthy-note"><b>Shënim</b><p>${r.note}</p></div><div class="safety">Recetat janë ide të përgjithshme për të rritur të shëndetshëm dhe nuk janë plan individual mjekësor, për humbje peshe apo trajtim të një gjendjeje shëndetësore.</div></div></div></div>`;hydrateDietPhotos(app);scrollTo(0,0);initReveal()}