const Family={
 key:'miranda_family_v1',profiles:[],active:null,
 init(){try{this.profiles=JSON.parse(localStorage.getItem(this.key)||'[]')}catch{this.profiles=[]}this.active=localStorage.getItem(this.key+'_active')||this.profiles[0]?.id||null;this.nav()},
 save(){localStorage.setItem(this.key,JSON.stringify(this.profiles));if(this.active)localStorage.setItem(this.key+'_active',this.active)},
 current(){return this.profiles.find(p=>p.id===this.active)||null},
 ageLabel(p){if(p.type==='baby')return `${p.ageMonths||0} muaj`;return `${p.ageYears||0} vjeç`},
 nav(){let h=document.querySelector('.premium-tools');if(!h||h.querySelector('.family-nav'))return;let b=document.createElement('button');b.className='family-nav nutrition-nav';b.textContent='Familja';b.onclick=()=>this.show();h.appendChild(b)},
 show(){let p=this.current();Ultra.modal(`<div class="u-modal-head"><div><small>MIRANDA FAMILY</small><h2>Shtëpia ime</h2></div><button onclick="Ultra.close()">×</button></div><div class="family-hero"><span>FAMILY HEALTH</span><h3>${p?`Profili aktiv: ${p.name}`:'Krijo profilin e parë'}</h3><p>Profile të ndara për bebe, fëmijë dhe të rritur. Ushqim, rutinë, gjumë dhe fitness në një vend.</p></div>${this.profiles.length?`<div class="family-profiles">${this.profiles.map(x=>`<button class="family-profile ${x.id===this.active?'active':''}" onclick="Family.select('${x.id}')"><b>${x.name}</b><small>${x.type==='baby'?'Bebe':x.type==='child'?'Fëmijë':'I rritur'} · ${this.ageLabel(x)}</small></button>`).join('')}</div>`:''}<div class="family-actions"><button onclick="Family.form()">+ Shto profil</button>${p?`<button onclick="Family.dashboard()">Hape profilin</button>`:''}</div>`)},
 select(id){this.active=id;this.save();this.show()},
 form(){Ultra.modal(`<div class="u-modal-head"><div><small>PROFIL I RI</small><h2>Anëtar i familjes</h2></div><button onclick="Ultra.close()">×</button></div><form class="family-form" onsubmit="Family.create(event)"><label>Emri<input name="name" required placeholder="Emri"></label><label>Profili<select name="type" onchange="Family.typeChange(this.value)"><option value="adult">I rritur</option><option value="child">Fëmijë</option><option value="baby">Bebe</option></select></label><div id="familyAge"><label>Mosha (vite)<input name="ageYears" type="number" min="1" max="120" required></label></div><div class="family-grid"><label>Gjinia<select name="sex"><option value="female">Femër</option><option value="male">Mashkull</option></select></label><label>Pesha (kg)<input name="weight" type="number" min="1" step="0.1"></label><label>Gjatësia (cm)<input name="height" type="number" min="30" step="0.1"></label><label>Aktiviteti<select name="activity"><option value="low">I ulët</option><option value="moderate">Mesatar</option><option value="high">I lartë</option></select></label></div><label>Objektivi<select name="goal"><option value="wellness">Shëndet & mirëqenie</option><option value="maintain">Mirëmbajtje</option><option value="lose">Humbje peshe</option><option value="gain">Shtim peshe</option><option value="muscle">Muskuj / fitness</option></select></label><label>Alergji / ushqime që shmangen<input name="allergies" placeholder="p.sh. vezë, arra"></label><button class="family-save" type="submit">Ruaj profilin</button></form>`)},
 typeChange(v){let a=document.querySelector('#familyAge');if(!a)return;a.innerHTML=v==='baby'?'<label>Mosha (muaj)<input name="ageMonths" type="number" min="0" max="36" required></label>':'<label>Mosha (vite)<input name="ageYears" type="number" min="1" max="120" required></label>'},
 create(e){e.preventDefault();let f=new FormData(e.target),o=Object.fromEntries(f.entries());o.id='p'+Date.now();o.weight=Number(o.weight)||null;o.height=Number(o.height)||null;o.ageYears=Number(o.ageYears)||null;o.ageMonths=Number(o.ageMonths)||null;this.profiles.push(o);this.active=o.id;this.save();this.dashboard()},
 dashboard(){let p=this.current();if(!p)return this.show();let baby=p.type==='baby',adult=p.type==='adult';Ultra.modal(`<div class="u-modal-head"><div><small>${baby?'BABY PROFILE':adult?'ADULT PROFILE':'CHILD PROFILE'}</small><h2>${p.name}</h2></div><button onclick="Ultra.close()">×</button></div><div class="family-summary"><div><span>Mosha</span><b>${this.ageLabel(p)}</b></div><div><span>Pesha</span><b>${p.weight?p.weight+' kg':'—'}</b></div><div><span>Gjatësia</span><b>${p.height?p.height+' cm':'—'}</b></div><div><span>Aktiviteti</span><b>${p.activity==='high'?'I lartë':p.activity==='moderate'?'Mesatar':'I ulët'}</b></div></div><div class="family-modules"><button onclick="Family.meals()"><span>USHQIMI</span><b>Çka me ngrënë</b><small>Receta dhe USDA sipas profilit</small></button><button onclick="Family.sleep()"><span>RUTINA</span><b>Gjumi & dita</b><small>${baby?'Gjumi, zgjimi dhe rutina e bebes':'Orari, gjumi dhe rikuperimi'}</small></button>${adult?`<button onclick="Family.fitness()"><span>FITNESS</span><b>Stërvitja</b><small>Aktivitet, pre/post workout dhe progres</small></button>`:''}<button onclick="Family.progress()"><span>PROGRESI</span><b>Pesha & gjatësia</b><small>Ruaj matjet pa humbur historikun</small></button></div><p class="family-note">Miranda përdor profilin për organizim dhe personalizim. Vlerat USDA tregojnë përbërjen e ushqimit; targetet shëndetësore sipas moshës do të shtohen vetëm me burime zyrtare të verifikuara.</p>`)},
 meals(){let p=this.current();Ultra.modal(`<div class="u-modal-head"><div><small>${p.name.toUpperCase()} · USHQIMI</small><h2>Plani ushqimor</h2></div><button onclick="Ultra.close()">×</button></div><div class="family-hero"><span>PROFILE AWARE</span><h3>${p.type==='baby'?'Receta sipas fazës së bebes':p.goal==='muscle'?'Ushqim për fitness':'Ushqim për profilin tënd'}</h3><p>Ky modul tash është lidhur me profilin. Hapi tjetër do të filtrojë bibliotekën Miranda sipas moshës, alergjive, aktivitetit dhe objektivit pa shpikur targete ushqyese.</p></div>`)},
 sleep(){let p=this.current();Ultra.modal(`<div class="u-modal-head"><div><small>${p.name.toUpperCase()} · RUTINA</small><h2>Gjumi & dita</h2></div><button onclick="Ultra.close()">×</button></div><div class="family-hero"><span>DAILY ROUTINE</span><h3>Regjistrimi i rutinës</h3><p>Do të mbajë orën e gjumit, zgjimit, kohën zgjuar dhe rutinën ditore. Rekomandimet sipas moshës nuk aktivizohen pa standarde zyrtare të verifikuara.</p></div>`)},
 fitness(){let p=this.current();Ultra.modal(`<div class="u-modal-head"><div><small>${p.name.toUpperCase()} · FITNESS</small><h2>Fitness Hub</h2></div><button onclick="Ultra.close()">×</button></div><div class="family-summary"><div><span>Objektivi</span><b>${p.goal==='muscle'?'Muskuj':p.goal==='lose'?'Humbje peshe':p.goal==='gain'?'Shtim peshe':'Mirëqenie'}</b></div><div><span>Aktiviteti</span><b>${p.activity==='high'?'I lartë':p.activity==='moderate'?'Mesatar':'I ulët'}</b></div></div><div class="family-modules"><button><span>WORKOUT</span><b>Plani i stërvitjes</b><small>Ditë stërvitjeje dhe pushimi</small></button><button><span>NUTRITION</span><b>Para / pas stërvitjes</b><small>Receta të lidhura me USDA</small></button><button><span>RECOVERY</span><b>Gjumi & rikuperimi</b><small>Rutina dhe progresi</small></button></div>`)},
 progress(){let p=this.current();Ultra.modal(`<div class="u-modal-head"><div><small>${p.name.toUpperCase()} · PROGRESI</small><h2>Matjet</h2></div><button onclick="Ultra.close()">×</button></div><form class="family-form" onsubmit="Family.measure(event)"><div class="family-grid"><label>Pesha (kg)<input name="weight" type="number" step="0.1" value="${p.weight||''}"></label><label>Gjatësia (cm)<input name="height" type="number" step="0.1" value="${p.height||''}"></label></div><button class="family-save">Ruaj matjen</button></form>`)},
 measure(e){e.preventDefault();let p=this.current(),f=new FormData(e.target);p.weight=Number(f.get('weight'))||p.weight;p.height=Number(f.get('height'))||p.height;p.history=p.history||[];p.history.push({date:new Date().toISOString(),weight:p.weight,height:p.height});this.save();this.dashboard()}
};
new MutationObserver(()=>{clearTimeout(window.__family);window.__family=setTimeout(()=>Family.nav(),150)}).observe(document.querySelector('#app'),{childList:true,subtree:true});setTimeout(()=>Family.init(),350);