const Nutrition={
 source:'USDA FoodData Central',api:'https://api.nal.usda.gov/fdc/v1',key:'DEMO_KEY',
 nutrientNames:['Energy','Protein','Total lipid (fat)','Carbohydrate, by difference','Fiber, total dietary','Sugars, total including NLEA','Sodium, Na','Calcium, Ca','Iron, Fe','Potassium, K','Vitamin C, total ascorbic acid','Vitamin D (D2 + D3)','Vitamin A, RAE','Fatty acids, total saturated','Cholesterol'],
 cleanIngredient(s){return s.replace(/^\s*[\d½¼¾⅓⅔\.\/–-]+\s*(g|kg|ml|l|lugë( çaji| gjelle)?|feta?|copë|grusht)?\s*/i,'').replace(/\([^)]*\)/g,'').split(',')[0].replace(/\b(i|e) (vogël|madhe|gatuar|zier|kulluar|copëtuar)\b/gi,'').trim()},
 async searchFood(q){let u=`${this.api}/foods/search?api_key=${this.key}&query=${encodeURIComponent(q)}&pageSize=5&dataType=Foundation,SR%20Legacy,FNDDS`;let r=await fetch(u);if(!r.ok)throw new Error('USDA API unavailable');let d=await r.json();return d.foods||[]},
 nutrients(food){let out={};(food.foodNutrients||[]).forEach(n=>{let name=n.nutrientName||n.nutrient?.name,unit=n.unitName||n.nutrient?.unitName,val=n.value??n.amount;if(name&&val!=null)out[name]={value:val,unit}});return out},
 card(food){let n=this.nutrients(food),rows=this.nutrientNames.filter(x=>n[x]).map(x=>`<div><span>${this.sq(x)}</span><b>${this.num(n[x].value)} ${n[x].unit||''}</b></div>`).join('');return `<article class="usda-food"><div class="usda-food-head"><div><small>FDC ID ${food.fdcId}</small><h3>${food.description}</h3></div><span>${food.dataType||'USDA'}</span></div><div class="nutrient-grid">${rows||'<p>Nuk u kthyen nutrientët kryesorë për këtë rekord.</p>'}</div><p class="per100">Vlerat e paraqitura janë siç kthehen nga rekordi USDA; për shumë rekorde bazë raportimi është për 100 g. Kontrollo përshkrimin dhe njësinë e rekordit para interpretimit.</p></article>`},
 sq(n){return({'Energy':'Energji','Protein':'Proteina','Total lipid (fat)':'Yndyrë totale','Carbohydrate, by difference':'Karbohidrate','Fiber, total dietary':'Fibra','Sugars, total including NLEA':'Sheqerna totale','Sodium, Na':'Natrium','Calcium, Ca':'Kalcium','Iron, Fe':'Hekur','Potassium, K':'Kalium','Vitamin C, total ascorbic acid':'Vitaminë C','Vitamin D (D2 + D3)':'Vitaminë D','Vitamin A, RAE':'Vitaminë A','Fatty acids, total saturated':'Yndyrë e ngopur','Cholesterol':'Kolesterol'})[n]||n},num(v){return Number(v).toLocaleString('sq-AL',{maximumFractionDigits:2})},
 async lookup(q){let box=document.querySelector('#nutritionResults');if(!box)return;box.innerHTML='<div class="nutrition-loading">Duke kërkuar në USDA FoodData Central…</div>';try{let foods=await this.searchFood(q);box.innerHTML=foods.length?foods.map(f=>this.card(f)).join(''):'<p class="u-empty">Nuk u gjet rekord USDA për këtë kërkim.</p>'}catch(e){box.innerHTML='<p class="u-empty">USDA API nuk u përgjigj. DEMO_KEY ka limit të ulët; provo përsëri më vonë.</p>'}},
 show(){Ultra.modal(`<div class="u-modal-head"><div><small>USDA FOODDATA CENTRAL</small><h2>Nutrition Lab</h2></div><button onclick="Ultra.close()">×</button></div><div class="usda-badge"><b>Burim zyrtar</b><span>FoodData Central · USDA Agricultural Research Service</span><small>Foundation Foods · FNDDS · SR Legacy</small></div><div class="u-search nutrition-search"><input id="nutritionQuery" placeholder="Kërko ushqim, p.sh. salmon raw" onkeydown="if(event.key==='Enter')Nutrition.lookup(this.value)"><button onclick="Nutrition.lookup(document.querySelector('#nutritionQuery').value)">Kërko USDA</button></div><div id="nutritionResults"><div class="nutrition-welcome"><b>15 nutrientë kryesorë</b><p>Energji, proteinë, yndyrë, karbohidrate, fibra, sheqerna, natrium, kalcium, hekur, kalium, vitaminat A/C/D, yndyrë e ngopur dhe kolesterol — vetëm kur rekordi USDA i përmban.</p></div></div><div class="usda-source"><b>Database</b><span>USDA FoodData Central. Të dhënat janë CC0/public domain. Miranda nuk shpik vlera që mungojnë.</span></div>`)},
 async recipe(t,i){let r=Ultra.all().find(x=>x._type===t&&x._i===i);if(!r)return;Ultra.modal(`<div class="u-modal-head"><div><small>USDA · INGREDIENT AUDIT</small><h2>${r.title}</h2></div><button onclick="Ultra.close()">×</button></div><p class="u-sub">Secili përbërës kërkohet veçmas në FoodData Central. Kjo dritare nuk pretendon total kalorik të recetës pa normalizim të saktë të peshës dhe yield-it.</p><div id="nutritionResults" class="ingredient-audit"></div>`);let box=document.querySelector('#nutritionResults');for(let ing of r.ingredients){let q=this.cleanIngredient(ing),row=document.createElement('div');row.className='ingredient-row';row.innerHTML=`<div><b>${ing}</b><small>${q}</small></div><span class="spin">○</span>`;box.appendChild(row);try{let f=(await this.searchFood(q))[0];row.innerHTML=f?`<div><b>${ing}</b><small>${f.description} · FDC ${f.fdcId}</small></div><button onclick="Nutrition.lookup('${q.replaceAll("'","\\'")}')">Detaje</button>`:`<div><b>${ing}</b><small>Pa përputhje automatike</small></div><span>—</span>`}catch{row.innerHTML=`<div><b>${ing}</b><small>API limit / unavailable</small></div><span>!</span>`;break}}},
 enhance(){let root=document.querySelector('.detail-copy,.diet-detail>div:last-child');if(!root||root.querySelector('.nutrition-entry'))return;let h=root.querySelector('h1');if(!h)return;let r=Ultra.all().find(x=>x.title===h.textContent);if(!r)return;let b=document.createElement('button');b.className='nutrition-entry';b.innerHTML='<span>USDA</span><div><b>Analiza ushqyese</b><small>Kontrollo përbërësit në FoodData Central</small></div><i>→</i>';b.onclick=()=>this.recipe(r._type,r._i);let actions=root.querySelector('.recipe-actions');actions?actions.after(b):h.after(b)},
 nav(){let h=document.querySelector('.premium-tools');if(h&&!h.querySelector('.nutrition-nav')){let b=document.createElement('button');b.className='nutrition-nav';b.textContent='USDA Nutrition';b.onclick=()=>this.show();h.appendChild(b)}}
};
new MutationObserver(()=>{clearTimeout(window.__nutrition);window.__nutrition=setTimeout(()=>{Nutrition.enhance();Nutrition.nav()},120)}).observe(document.querySelector('#app'),{childList:true,subtree:true});setTimeout(()=>{Nutrition.enhance();Nutrition.nav()},250);