const Nutrition={
 db:null,loading:null,source:'USDA FoodData Central + USDA Child Nutrition Database',
 aliases:{'tërshërë':'oat','qumësht':'milk','mollë':'apple','kos':'yogurt','banane':'banana','arra':'walnut','vezë':'egg','spinaq':'spinach','domate':'tomato','avokado':'avocado','boronica':'blueberry','dardhë':'pear','kërpudha':'mushroom','kakao':'cocoa','bukë':'bread','gjizë':'cottage cheese','kiwi':'kiwi','pulë':'chicken','quinoa':'quinoa','oriz':'rice','ton':'tuna','sallatë':'lettuce','kastravec':'cucumber','qiqra':'chickpea','bulgur':'bulgur','patate e ëmbël':'sweet potato','patate':'potato','makarona':'pasta','kungulleshkë':'zucchini','spec':'pepper','thjerrëza':'lentil','karotë':'carrot','qepë':'onion','feta':'feta','gjeldeti':'turkey','salmon':'salmon','brokoli':'broccoli','merluc':'cod','bizele':'peas','fasule':'beans','tofu':'tofu','gjalpë kikiriku':'peanut butter','hummus':'hummus','chia':'chia','fara kungulli':'pumpkin seed','limon':'lemon','majdanoz':'parsley','kopër':'dill','misër':'corn','luleshtrydhe':'strawberry','portokall':'orange','pjeshkë':'peach','kumbull':'plum','mango':'mango','borzilok':'basil','lulelakër':'cauliflower','kungull':'pumpkin','mish viçi':'beef','djathë':'cheese','gjalpë':'butter'},
 clean(s){return String(s||'').toLowerCase().replace(/^\s*[\d½¼¾⅓⅔\.\/–-]+\s*(g|kg|ml|l|lugë( çaji| gjelle)?|feta?|copë|grusht)?\s*/i,'').replace(/\([^)]*\)/g,'').split(',')[0].trim()},
 english(q){q=this.clean(q);let keys=Object.keys(this.aliases).sort((a,b)=>b.length-a.length),k=keys.find(x=>q.includes(x));return k?this.aliases[k]:q},
 esc(s){return String(s).replaceAll("'","''")},
 async init(){if(this.db)return this.db;if(this.loading)return this.loading;this.loading=(async()=>{if(typeof initSqlJs!=='function')throw new Error('SQL.js nuk u ngarkua');let SQL=await initSqlJs({locateFile:f=>`https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.11.0/${f}`});let res=await fetch('miranda_usda_complete.sqlite?v=13',{cache:'no-store'});if(!res.ok)throw new Error(`Database HTTP ${res.status}`);let bytes=new Uint8Array(await res.arrayBuffer());this.db=new SQL.Database(bytes);return this.db})();return this.loading},
 query(sql){let r=this.db.exec(sql);if(!r.length)return[];return r[0].values.map(v=>Object.fromEntries(r[0].columns.map((c,i)=>[c,v[i]])))},
 async search(q,limit=25){await this.init();let term=this.english(q);if(!term)return[];return this.query(`SELECT source,food_id,description,data_type,publication_date FROM foods WHERE lower(description) LIKE '%${this.esc(term)}%' ORDER BY CASE source WHEN 'foundation' THEN 0 ELSE 1 END, length(description) LIMIT ${Number(limit)||25}`)},
 nutrients(source,id){return this.query(`SELECT n.name,n.unit,n.nutrient_number,fn.amount FROM food_nutrients fn JOIN nutrients n ON n.source=fn.source AND n.nutrient_id=fn.nutrient_id WHERE fn.source='${this.esc(source)}' AND fn.food_id=${Number(id)} AND fn.amount IS NOT NULL ORDER BY n.name`)},
 portions(source,id){return this.query(`SELECT amount,unit,gram_weight,description FROM portions WHERE source='${this.esc(source)}' AND food_id=${Number(id)} LIMIT 30`)},
 sq(n){let m={'Energy':'Energji','Food Energy':'Energji','Energy (Atwater General Factors)':'Energji','Energy (Atwater Specific Factors)':'Energji','Protein':'Proteina','Total lipid (fat)':'Yndyrna totale','Total Fat':'Yndyrna totale','Carbohydrate, by difference':'Karbohidrate','Carbohydrate':'Karbohidrate','Fiber, total dietary':'Fibra','Total Dietary Fiber':'Fibra','Sugars, Total':'Sheqerna','Sugars, total including NLEA':'Sheqerna','Total Sugars':'Sheqerna','Sodium, Na':'Natrium','Sodium':'Natrium','Calcium, Ca':'Kalcium','Calcium':'Kalcium','Iron, Fe':'Hekur','Iron':'Hekur','Potassium, K':'Kalium','Potassium':'Kalium','Zinc, Zn':'Zink','Zinc':'Zink','Vitamin D (D2 + D3)':'Vitaminë D','Vitamin D':'Vitaminë D','Vitamin A, RAE':'Vitaminë A','Vitamin A':'Vitaminë A','Folate, total':'Folat','Folate':'Folat','Vitamin C, total ascorbic acid':'Vitaminë C','Vitamin C':'Vitaminë C','Ash':'Hiri mineral','Citric acid':'Acid citrik','Copper, Cu':'Bakër','Fructose':'Fruktozë','Glucose':'Glukozë','Lactose':'Laktozë','Magnesium, Mg':'Magnez','Malic acid':'Acid malik','Maltose':'Maltozë','Manganese, Mn':'Mangan','Niacin':'Niacinë','Nitrogen':'Azot','Oxalic acid':'Acid oksalik','Phosphorus, P':'Fosfor'};return m[n]||n},
 num(v){return Number(v).toLocaleString('sq-AL',{maximumFractionDigits:3})},
 essential(ns){let groups=[['Energji',['energy','food energy']],['Proteina',['protein']],['Karbohidrate',['carbohydrate']],['Yndyrna',['total lipid','total fat']],['Fibra',['fiber']],['Sheqerna',['sugars, total','total sugars']],['Natrium',['sodium']],['Kalium',['potassium']],['Kalcium',['calcium']],['Hekur',['iron']],['Zink',['zinc']],['Vitaminë D',['vitamin d']],['Vitaminë A',['vitamin a']],['Folat',['folate']]];let used=new Set(),out=[];for(let [label,terms] of groups){let n=ns.find((x,i)=>!used.has(i)&&terms.some(t=>x.name.toLowerCase().includes(t)));if(n){used.add(ns.indexOf(n));out.push({...n,_label:label})}}return out},
 nutrientCards(ns,essential=false){return ns.map(n=>`<div><span>${essential?n._label:this.sq(n.name)}</span><b>${n.amount==null?'—':this.num(n.amount)} ${n.unit||''}</b></div>`).join('')},
 toggleFull(id){let el=document.getElementById(id),b=document.querySelector(`[data-target="${id}"]`);if(!el||!b)return;let open=el.hidden;el.hidden=!open;b.textContent=open?'Fshih analizën e plotë':'Shfaq analizën e plotë'},
 async detail(source,id){await this.init();let f=this.query(`SELECT * FROM foods WHERE source='${this.esc(source)}' AND food_id=${Number(id)} LIMIT 1`)[0];if(!f)return;let ns=this.nutrients(source,id),core=this.essential(ns),ps=this.portions(source,id),fullId=`full-${source}-${id}`;Ultra.modal(`<div class="u-modal-head"><div><small>${source==='foundation'?'FDC ID':'CN CODE'} ${id}</small><h2>${f.description}</h2></div><button onclick="Ultra.close()">×</button></div><div class="usda-badge"><b>${source==='foundation'?'Foundation Foods 2026-04-30':'CNDB 2026.07'}</b><span>${core.length} vlera kryesore · ${ns.length} gjithsej në rekord</span><small>Vlerat e plota USDA ruhen në databazë; këtu shfaqen fillimisht vetëm ato më të dobishmet.</small></div><div class="nutrient-grid">${this.nutrientCards(core,true)}</div>${ns.length>core.length?`<button class="nutrition-entry" data-target="${fullId}" onclick="Nutrition.toggleFull('${fullId}')"><span>USDA</span><div><b>Shfaq analizën e plotë</b><small>${ns.length} nutrientë nga rekordi origjinal</small></div><i>+</i></button><div id="${fullId}" hidden><div class="nutrient-grid" style="margin-top:16px">${this.nutrientCards(ns)}</div></div>`:''}${ps.length?`<div class="usda-source"><b>Porcione / masa</b><span>${ps.map(p=>`${p.amount??''} ${p.unit||p.description||''}${p.gram_weight?` · ${p.gram_weight} g`:''}`).join(' · ')}</span></div>`:''}`)},
 async lookup(q){let box=document.querySelector('#nutritionResults');if(!box)return;box.innerHTML='<p class="u-empty">Duke kërkuar në databazën e plotë…</p>';try{let hits=await this.search(q,30);box.innerHTML=hits.length?hits.map(r=>`<article class="usda-food" onclick="Nutrition.detail('${r.source}',${r.food_id})"><div class="usda-food-head"><div><small>${r.source==='foundation'?'FDC ID':'CN CODE'} ${r.food_id}</small><h3>${r.description}</h3></div><span>${r.source==='foundation'?'Foundation':'CNDB'}</span></div><p class="per100">Preke për vlerat kryesore dhe analizën e plotë USDA.</p></article>`).join(''):'<p class="u-empty">Nuk u gjet rekord në databazën USDA.</p>'}catch(e){box.innerHTML=`<p class="u-empty">Gabim gjatë hapjes së databazës: ${e.message}</p>`}},
 async show(){Ultra.modal(`<div class="u-modal-head"><div><small>COMPLETE LOCAL USDA DATABASE</small><h2>Nutrition Lab</h2></div><button onclick="Ultra.close()">×</button></div><div class="usda-badge"><b>9,533 ushqime · 190,626 vlera ushqyese</b><span>Foundation Foods 2026-04-30 + CNDB 2026.07</span><small>Miranda lexon direkt databazën e plotë USDA.</small></div><div class="u-search nutrition-search"><input id="nutritionQuery" placeholder="Kërko: salmon, brokoli, vezë..." onkeydown="if(event.key==='Enter')Nutrition.lookup(this.value)"><button onclick="Nutrition.lookup(document.querySelector('#nutritionQuery').value)">Kërko</button></div><div id="nutritionResults"><div class="nutrition-welcome"><b>Databaza e plotë USDA</b><p>Rezultati shfaq fillimisht vlerat ushqyese kryesore. Analiza e plotë mbetet një prekje larg.</p></div></div>`);try{await this.init()}catch(e){let b=document.querySelector('#nutritionResults');if(b)b.innerHTML=`<p class="u-empty">${e.message}</p>`}},
 async recipe(t,i){let r=Ultra.all().find(x=>x._type===t&&x._i===i);if(!r)return;await this.init();let matched=[];for(let ing of r.ingredients){let h=await this.search(ing,1);matched.push([ing,h[0]||null])}Ultra.modal(`<div class="u-modal-head"><div><small>COMPLETE USDA · RECIPE MATCH</small><h2>${r.title}</h2></div><button onclick="Ultra.close()">×</button></div><div class="ingredient-audit">${matched.map(([ing,m])=>`<div class="ingredient-row"><div><b>${ing}</b><small>${m?`${m.description} · ${m.source==='foundation'?'FDC':'CN'} ${m.food_id}`:'Pa përputhje të sigurt'}</small></div>${m?`<button onclick="Nutrition.detail('${m.source}',${m.food_id})">Detaje</button>`:'<span>—</span>'}</div>`).join('')}</div><div class="usda-source"><b>Mbulimi</b><span>${matched.filter(x=>x[1]).length}/${matched.length} përbërës u lidhën me databazën e plotë.</span></div>`)},
 enhance(){let root=document.querySelector('.detail-copy,.diet-detail>div:last-child');if(!root||root.querySelector('.nutrition-entry'))return;let h=root.querySelector('h1');if(!h)return;let r=Ultra.all().find(x=>x.title===h.textContent);if(!r)return;let b=document.createElement('button');b.className='nutrition-entry';b.innerHTML='<span>USDA</span><div><b>Analiza ushqyese</b><small>Vlerat kryesore + analiza e plotë USDA</small></div><i>→</i>';b.onclick=()=>this.recipe(r._type,r._i);let actions=root.querySelector('.recipe-actions');actions?actions.after(b):h.after(b)},
 nav(){let h=document.querySelector('.premium-tools');if(h&&!h.querySelector('.nutrition-nav')){let b=document.createElement('button');b.className='nutrition-nav';b.textContent='USDA Complete';b.onclick=()=>this.show();h.appendChild(b)}}
};
new MutationObserver(()=>{clearTimeout(window.__nutrition);window.__nutrition=setTimeout(()=>{Nutrition.enhance();Nutrition.nav()},120)}).observe(document.querySelector('#app'),{childList:true,subtree:true});setTimeout(()=>{Nutrition.enhance();Nutrition.nav()},250);