const Premium={
 themeKey:'miranda_theme_v9',pantryKey:'miranda_pantry_v9',profileKey:'miranda_profile_v9',recentKey:'miranda_recent_v9',portion:1,
 init(){this.applyTheme();this.injectDesktopNav();this.decorateCards();this.trackDetails();this.registerPWA()},
 applyTheme(){document.documentElement.dataset.theme=localStorage.getItem(this.themeKey)||'dark'},
 toggleTheme(){let v=document.documentElement.dataset.theme==='light'?'dark':'light';localStorage.setItem(this.themeKey,v);document.documentElement.dataset.theme=v;Ultra.toast(v==='light'?'Light mode':'Dark mode')},
 injectDesktopNav(){document.querySelectorAll('header').forEach(h=>{if(h.querySelector('.premium-tools'))return;let d=document.createElement('div');d.className='premium-tools';d.innerHTML='<button onclick="Premium.toggleTheme()">◐</button><button onclick="Premium.showCollections()">Koleksione</button><button onclick="Premium.showPantry()">Pantry</button><button onclick="Premium.showProfile()">Profili</button>';h.appendChild(d)})},
 decorateCards(){document.querySelectorAll('.recipe-card,.diet-card').forEach(card=>{if(card.querySelector('.premium-heart'))return;let title=card.querySelector('h3')?.textContent,r=Ultra.all().find(x=>x.title===title);if(!r)return;let b=document.createElement('button');b.className='premium-heart';b.dataset.fav=`${r._type}:${r._i}`;b.innerHTML='♡';b.onclick=e=>{e.stopPropagation();Ultra.toggleFav(r._type,r._i)};card.prepend(b)});Ultra.renderSaved()},
 trackDetails(){let h=document.querySelector('.detail-copy h1,.diet-detail h1');if(!h)return;let r=Ultra.all().find(x=>x.title===h.textContent);if(!r)return;let a=Ultra.get(this.recentKey,[]).filter(x=>x!==`${r._type}:${r._i}`);a.unshift(`${r._type}:${r._i}`);Ultra.set(this.recentKey,a.slice(0,8));this.addPremiumDetail(r)},
 addPremiumDetail(r){let root=document.querySelector('.detail-copy,.diet-detail>div:last-child');if(!root||root.querySelector('.premium-detail'))return;let d=document.createElement('section');d.className='premium-detail';d.innerHTML=`<div class="portion-box"><span>Porcionet</span><button onclick="Premium.scale('${r._type}',${r._i},.5)">½×</button><button class="active" onclick="Premium.scale('${r._type}',${r._i},1)">1×</button><button onclick="Premium.scale('${r._type}',${r._i},2)">2×</button><button onclick="Premium.scale('${r._type}',${r._i},4)">4×</button></div><div class="premium-actions"><button onclick="Premium.printRecipe()">Print / PDF</button><button onclick="Premium.addPantryRecipe('${r._type}',${r._i})">+ Pantry</button><button onclick="Premium.substitutions('${r._type}',${r._i})">Zëvendësime</button></div>`;let first=root.querySelector('.detail-section');first?root.insertBefore(d,first):root.appendChild(d)},
 scale(t,i,n){this.portion=n;let r=Ultra.all().find(x=>x._type===t&&x._i===i),ul=document.querySelector('.detail-section ul');if(!ul)return;ul.innerHTML=r.ingredients.map(x=>`<li>${n===1?x:`${n}× ${x}`}</li>`).join('');document.querySelectorAll('.portion-box button').forEach(b=>b.classList.toggle('active',b.textContent===`${n===.5?'½':n}×`));Ultra.toast(`Porcionet: ${n}×`)},
 printRecipe(){window.print()},
 substitutions(t,i){let r=Ultra.all().find(x=>x._type===t&&x._i===i);Ultra.modal(`<div class="u-modal-head"><div><small>SMART SUBSTITUTIONS</small><h2>Zëvendësime</h2></div><button onclick="Ultra.close()">×</button></div><div class="sub-list"><p>Për ${r.title}, zëvendësimet duhen bërë sipas funksionit të përbërësit, jo vetëm sipas shijes.</p><div><b>Kos natyral</b><span>→ alternativë e pasterizuar pa sheqer, kur receta e lejon.</span></div><div><b>Quinoa / bulgur / oriz</b><span>→ mund të ndërrohen mes vete në bowl për të rritur, me kohën përkatëse të gatimit.</span></div><div><b>Pulë</b><span>→ gjeldeti i gatuar plotësisht në receta të ngjashme për të rritur.</span></div><div><b>Baby recipes</b><span>→ mos zëvendëso alergjenë ose tekstura pa marrë parasysh moshën dhe historinë e fëmijës.</span></div></div>`)},
 showCollections(){let all=Ultra.all(),recent=Ultra.get(this.recentKey,[]);Ultra.modal(`<div class="u-modal-head"><div><small>DISCOVER</small><h2>Koleksione</h2></div><button onclick="Ultra.close()">×</button></div><div class="collection-grid"><button onclick="Ultra.close();Premium.collection('quick')"><b>Nën 20 minuta</b><span>${all.filter(x=>parseInt(x.time)<=20).length} receta</span></button><button onclick="Ultra.close();Premium.collection('breakfast')"><b>Mëngjese</b><span>Fillim i lehtë</span></button><button onclick="Ultra.close();Premium.collection('protein')"><b>Me proteinë</b><span>Vezë, pulë, peshk, bishtajore</span></button><button onclick="Ultra.close();Premium.collection('recent')"><b>Shikuar së fundmi</b><span>${recent.length} receta</span></button></div>`)},
 collection(k){let a=Ultra.all();if(k==='quick')a=a.filter(x=>parseInt(x.time)<=20);if(k==='breakfast')a=a.filter(x=>x.cat==='Mëngjes');if(k==='protein')a=a.filter(x=>['Proteinë','Bishtajore'].includes(x.cat));if(k==='recent'){let ids=Ultra.get(this.recentKey,[]);a=a.filter(x=>ids.includes(`${x._type}:${x._i}`))}Ultra.modal(`<div class="u-modal-head"><div><small>KOLEKSION</small><h2>${k==='recent'?'Shikuar së fundmi':'Recetat'}</h2></div><button onclick="Ultra.close()">×</button></div><div class="u-results">${a.map(r=>`<button onclick="Ultra.close();Ultra.open(Ultra.all().find(x=>x._type==='${r._type}'&&x._i===${r._i}))"><span>${r.icon}</span><div><b>${r.title}</b><small>${r.cat} · ${r.time}</small></div><i>→</i></button>`).join('')}</div>`)},
 pantry(){return Ultra.get(this.pantryKey,[])},showPantry(){let p=this.pantry();Ultra.modal(`<div class="u-modal-head"><div><small>ÇKA KE NË SHTËPI?</small><h2>Pantry</h2></div><button onclick="Ultra.close()">×</button></div><div class="pantry-add"><input id="pantryInput" placeholder="p.sh. pulë"><button onclick="Premium.addPantry()">Shto</button></div><div class="pantry-tags">${p.map((x,i)=>`<button onclick="Premium.removePantry(${i})">${x} ×</button>`).join('')}</div><button class="u-primary" onclick="Premium.fridge()">Gjej receta me këto ushqime</button>`)},
 addPantry(){let e=document.querySelector('#pantryInput'),v=e?.value.trim();if(!v)return;let p=this.pantry();if(!p.includes(v))p.push(v);Ultra.set(this.pantryKey,p);this.showPantry()},removePantry(i){let p=this.pantry();p.splice(i,1);Ultra.set(this.pantryKey,p);this.showPantry()},addPantryRecipe(t,i){let r=Ultra.all().find(x=>x._type===t&&x._i===i),p=this.pantry();r.ingredients.forEach(x=>{let v=x.replace(/^\d+[\d–\-\/\. ]*\s*(g|ml|lugë|copë|feta)?\s*/i,'').split(',')[0];if(v&&!p.includes(v))p.push(v)});Ultra.set(this.pantryKey,p);Ultra.toast('Përbërësit u shtuan në Pantry')},
 fridge(){let p=this.pantry().map(x=>x.toLowerCase()),a=Ultra.all().map(r=>({...r,score:p.filter(x=>r.ingredients.join(' ').toLowerCase().includes(x)).length})).filter(x=>x.score).sort((a,b)=>b.score-a.score);Ultra.modal(`<div class="u-modal-head"><div><small>FRIDGE MATCH</small><h2>Mund t’i përgatitësh</h2></div><button onclick="Ultra.close()">×</button></div><div class="u-results">${a.length?a.map(r=>`<button onclick="Ultra.close();Ultra.open(Ultra.all().find(x=>x._type==='${r._type}'&&x._i===${r._i}))"><span>${r.icon}</span><div><b>${r.title}</b><small>${r.score} përbërës përputhen</small></div><i>→</i></button>`).join(''):'<p class="u-empty">Shto disa përbërës në Pantry.</p>'}</div>`)},
 showProfile(){let p=Ultra.get(this.profileKey,{babyAge:'',diet:'standard'});Ultra.modal(`<div class="u-modal-head"><div><small>PERSONALIZIM</small><h2>Profili</h2></div><button onclick="Ultra.close()">×</button></div><div class="profile-form"><label>Mosha e bebit<select id="babyAge"><option value="">Pa profil bebe</option>${[6,7,8,9,10,11,12].map(n=>`<option ${p.babyAge==n?'selected':''}>${n}</option>`).join('')}</select></label><label>Preferenca<select id="diet"><option value="standard">Standard</option><option value="vegetarian" ${p.diet==='vegetarian'?'selected':''}>Vegjetariane</option></select></label><button class="u-primary" onclick="Premium.saveProfile()">Ruaje profilin</button></div>`)},saveProfile(){Ultra.set(this.profileKey,{babyAge:document.querySelector('#babyAge').value,diet:document.querySelector('#diet').value});Ultra.close();Ultra.toast('Profili u ruajt')},
 daily(){let a=Ultra.all(),d=Math.floor(Date.now()/86400000)%a.length;return a[d]},
 showDaily(){let r=this.daily();Ultra.modal(`<div class="u-modal-head"><div><small>RECIPE OF THE DAY</small><h2>Sot në Miranda</h2></div><button onclick="Ultra.close()">×</button></div><div class="daily-card"><span>${r.icon}</span><h2>${r.title}</h2><p>${r.desc}</p><button class="u-primary" onclick="Ultra.close();Ultra.open(Ultra.all().find(x=>x._type==='${r._type}'&&x._i===${r._i}))">Hape recetën</button></div>`)},
 safety(){Ultra.modal(`<div class="u-modal-head"><div><small>BABY SAFETY CENTER</small><h2>Siguria</h2></div><button onclick="Ultra.close()">×</button></div><div class="safety-center"><article><b>Tekstura</b><p>Përshtate me zhvillimin dhe aftësinë e fëmijës, jo vetëm me numrin e muajve.</p></article><article><b>Alergjenët</b><p>Prezanto ushqimet alergjene me kujdes dhe ndiq këshillën profesionale kur ka histori alergjie ose ekzemë të rëndë.</p></article><article><b>Mbikëqyrja</b><p>Fëmija duhet të jetë ulur drejt dhe i mbikëqyrur gjatë ngrënies.</p></article><article><b>Nën 12 muaj</b><p>Mos jep mjaltë. Mos shto kripë ose sheqer në ushqimet e bebit.</p></article></div>`)},
 registerPWA(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
};
const oldHub=Ultra.showHub.bind(Ultra);Ultra.showHub=function(){this.modal(`<div class="u-modal-head"><div><small>MIRANDA V9 · ULTRA</small><h2>Qendra Miranda</h2></div><button onclick="Ultra.close()">×</button></div><div class="hub-grid premium-hub"><button onclick="Ultra.close();home()"><span>🍼</span><b>Baby Table</b><small>6–12 muaj</small></button><button onclick="Ultra.close();openDiet()"><span>🥗</span><b>Healthy Table</b><small>Receta healthy</small></button><button onclick="Ultra.close();Premium.showDaily()"><span>◉</span><b>Receta e ditës</b><small>Zgjedhje dinamike</small></button><button onclick="Ultra.close();Premium.showCollections()"><span>▦</span><b>Koleksione</b><small>Zbulo receta</small></button><button onclick="Ultra.close();Premium.showPantry()"><span>⌂</span><b>Pantry</b><small>Çka ke në shtëpi</small></button><button onclick="Ultra.close();Premium.safety()"><span>♡</span><b>Baby Safety</b><small>Qendra e sigurisë</small></button><button onclick="Ultra.close();Ultra.showPlanner()"><span>□</span><b>Meal Planner</b><small>Java jote</small></button><button onclick="Ultra.close();Premium.showProfile()"><span>○</span><b>Profili</b><small>Personalizim</small></button></div>`) };
new MutationObserver(()=>{clearTimeout(window.__premium);window.__premium=setTimeout(()=>Premium.init(),90)}).observe(document.querySelector('#app'),{childList:true,subtree:true});setTimeout(()=>Premium.init(),120);