/* Miranda V10 recipe expansion: structured realistic recipes generated from curated meal templates. */
const MIRANDA_ING={
 breakfast:[['Tërshërë me mollë & kanellë','🥣',['50 g tërshërë','200 ml qumësht ose ujë','1 mollë e vogël','Kanellë']],['Kos me banane & arra','🍌',['180 g kos natyral','1 banane e vogël','15 g arra të copëtuara','1 lugë tërshërë']],['Omëletë me spinaq & domate','🍳',['2 vezë','50 g spinaq','1 domate e vogël','1 lugë çaji vaj ulliri']],['Toast me avokado & vezë','🥑',['2 feta bukë integrale','½ avokado','1 vezë','Limon']],['Porridge me boronica','🫐',['50 g tërshërë','200 ml qumësht','80 g boronica','1 lugë fara chia']],['Kos me dardhë & fara','🍐',['180 g kos natyral','1 dardhë','1 lugë fara chia','Kanellë']],['Vezë me kërpudha','🍄',['2 vezë','80 g kërpudha','30 g spinaq','1 lugë çaji vaj ulliri']],['Tërshërë me kakao & banane','🥣',['50 g tërshërë','200 ml qumësht','½ banane','1 lugë çaji kakao pa sheqer']],['Toast me gjizë & domate','🍅',['2 feta bukë integrale','80 g gjizë','1 domate','Barishte']],['Smoothie bowl me kos','🥝',['150 g kos natyral','1 banane e vogël','1 kiwi','30 g tërshërë']]],
 lunch:[['Pulë me quinoa & perime','🥗',['130 g gjoks pule','65 g quinoa','150 g perime të përziera','1 lugë çaji vaj ulliri']],['Oriz integral me ton','🍚',['70 g oriz integral','100 g ton në ujë i kulluar','120 g perime','Limon']],['Wrap integral me pulë','🌯',['1 tortilla integrale','110 g pulë e gatuar','Sallatë, domate, kastravec','2 lugë kos natyral']],['Bowl me qiqra & bulgur','🫘',['130 g qiqra të ziera','65 g bulgur','150 g perime','Limon dhe majdanoz']],['Sallatë me vezë & patate','🥚',['2 vezë','180 g patate','120 g sallatë dhe domate','1 lugë çaji vaj ulliri']],['Makarona integrale me ton','🍝',['75 g makarona integrale','100 g ton','120 g domate të copëtuara','Spinaq']],['Pulë me kuskus & perime','🍗',['130 g pulë','65 g kuskus integral','150 g kungulleshkë dhe spec','Limon']],['Thjerrëza me oriz integral','🍲',['80 g thjerrëza të ziera','60 g oriz integral','Karotë, qepë dhe domate','Majdanoz']],['Sallatë mesdhetare me qiqra','🥒',['130 g qiqra','Domate, kastravec, spec','30 g djathë feta','1 lugë çaji vaj ulliri']],['Bowl me gjeldeti & oriz','🍚',['130 g gjeldeti','65 g oriz integral','150 g brokoli dhe karotë','Limon']]],
 dinner:[['Salmon me patate & brokoli','🐟',['150 g salmon','200 g patate','160 g brokoli','Limon']],['Pulë në furrë me perime','🍗',['150 g pulë','200 g kungulleshkë, spec dhe karotë','150 g patate','1 lugë çaji vaj ulliri']],['Supë me thjerrëza & perime','🍲',['80 g thjerrëza','1 karotë','½ qepë','150 g domate','50 g spinaq']],['Merluc me oriz & bizele','🐟',['150 g merluc','65 g oriz','100 g bizele','Limon']],['Chili me fasule të kuqe','🫘',['150 g fasule të kuqe të ziera','150 g domate','½ spec','½ qepë','60 g oriz integral']],['Gjeldeti me patate të ëmbël','🍠',['150 g gjeldeti','200 g patate e ëmbël','150 g brokoli','Barishte']],['Makarona me thjerrëza','🍝',['75 g makarona integrale','100 g thjerrëza të ziera','150 g salcë domateje','Spinaq']],['Frittata me perime','🥚',['3 vezë','150 g kungulleshkë dhe spec','40 g spinaq','30 g djathë']],['Qiqra me spinaq & domate','🫘',['150 g qiqra','100 g spinaq','150 g domate','60 g bulgur']],['Pulë me brokoli & oriz','🥦',['150 g pulë','160 g brokoli','65 g oriz integral','Limon']]],
 snack:[['Kos me manaferra','🫐',['150 g kos natyral','100 g manaferra','10 g fara chia']],['Mollë me gjalpë kikiriku','🍎',['1 mollë','15 g gjalpë kikiriku 100%']],['Karotë & hummus','🥕',['120 g karotë','50 g hummus']],['Banane me kos','🍌',['1 banane e vogël','120 g kos natyral']],['Dardhë & arra','🍐',['1 dardhë','15 g arra']],['Kastravec me kos','🥒',['150 g kastravec','100 g kos natyral','Kopër']],['Toast integral me gjizë','🍞',['1 fetë bukë integrale','60 g gjizë','Domate']],['Fruta & fara','🥝',['150 g fruta të stinës','15 g fara kungulli']],['Vezë e zier & domate','🥚',['1 vezë','1 domate']],['Kos me tërshërë','🥣',['150 g kos natyral','25 g tërshërë','Kanellë']]],
 veggie:[['Curry i butë me qiqra','🍛',['150 g qiqra','150 g domate','100 g spinaq','60 g oriz integral']],['Burger me fasule','🫘',['150 g fasule të ziera','30 g tërshërë','½ qepë','Sallatë']],['Tofu me brokoli & oriz','🥦',['150 g tofu','160 g brokoli','65 g oriz integral','Limon']],['Bowl me thjerrëza & quinoa','🥗',['130 g thjerrëza të ziera','65 g quinoa','150 g perime','Majdanoz']],['Makarona me qiqra & domate','🍝',['75 g makarona integrale','120 g qiqra','150 g domate','Spinaq']],['Patate e ëmbël me fasule','🍠',['220 g patate e ëmbël','130 g fasule të zeza','Domate','Kos natyral']],['Supë krem me perime & fasule','🥣',['200 g perime të përziera','120 g fasule të bardha','½ qepë','Barishte']],['Bulgur me perime & qiqra','🥗',['65 g bulgur','130 g qiqra','180 g perime','Limon']],['Omëletë me perime & djathë','🍳',['2 vezë','150 g perime','30 g djathë','Sallatë']],['Qofte me thjerrëza','🫘',['150 g thjerrëza të ziera','30 g tërshërë','½ karotë','Sallatë']]]};
function mkHealthy(base,cat,n){let [title,icon,ingredients]=base;let mins=cat==='Snack'?5+(n%3)*3:cat==='Mëngjes'?10+(n%4)*3:20+(n%5)*5;let desc=`Recetë e balancuar me përbërës të zakonshëm, e përshtatshme për një ${cat.toLowerCase()} praktik dhe të ushqyeshëm.`;let steps=[`Përgatit dhe mat të gjithë përbërësit para gatimit.`,`Gatuaj përbërësit që kërkojnë nxehtësi derisa të jenë plotësisht të gatuar dhe me teksturë të përshtatshme.`,`Bashko përbërësit, rregullo konsistencën me pak ujë ose lëng limoni kur duhet dhe përzieji mirë.`,`Shërbeje të freskët dhe ruaj veçmas çdo porcion që nuk është prekur gjatë ngrënies.`];if(cat==='Snack')steps=['Laji dhe përgatiti përbërësit.','Prit ose përzieji në madhësi praktike për servirje.','Shërbeje menjëherë ose mbaje të ftohtë kur përmban kos apo vezë.'];return{cat,icon,title:`${title} · ${n+1}`,time:`${mins} min`,desc,ingredients:[...ingredients],steps,note:'Fokusi është te ushqimet minimalisht të përpunuara, perimet/frutat, drithërat dhe burimet e proteinës; përshtat porcionin me nevojat individuale.'}}
const expandedDietRecipes=[];[['breakfast','Mëngjes'],['lunch','Drekë'],['dinner','Darkë'],['snack','Snack'],['veggie','Vegjetariane']].forEach(([key,cat])=>{for(let round=0;round<3;round++)MIRANDA_ING[key].forEach((b,i)=>expandedDietRecipes.push(mkHealthy(b,cat,round*10+i)))});
/* 150 expanded healthy recipes; existing recipes remain available too. */
dietRecipes.push(...expandedDietRecipes);
window.MIRANDA_RECIPE_COUNT=recipes.length+dietRecipes.length;
