const Ultra={
 keyFav:'miranda_favorites_v8',keyPlan:'miranda_plan_v8',keyShop:'miranda_shop_v8',
 get(k,d=[]){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))},
 favs(){return this.get(this.keyFav)},toggleFav(type,i){let a=this.favs(),id=`${type}:${i}`;a=a.includes(id)?a.filter(x=>x!==id):[...a,id];this.set(this.keyFav,a);this.toast(a.includes(id)?'U ruajt te të preferuarat':'U hoq nga të preferuarat');this.renderSaved()},
 all(){return [...recipes.map((r,i)=>({...r,_type:'baby',_i:i})),...dietRecipes.map((r,i)=>({...r,_type:'diet',_i:i}))]},
 open(r){r._type==='baby'?openRecipe(r._i):openDietRecipe(r._i)},
 toast(t){let e=document.createElement('div');e.className='ultra-toast';e.textContent=t;document.body.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),250)},1800)},
 search(q=''){let s=q.trim().toLowerCase();return this.all().filter(r=>!s||[r.title,r.cat,r.desc,...(r.ingredients||[])].join(' ').toLowerCase().includes(s))},
 showSearch(){this.modal(`<div class="u-modal-head"><div><small>KËRKO NË MIRANDA</small><h2>Çka po kërkon?</h2></div><button onclick="Ultra.close()">×</button></div><div class="u-search"><input id="uSearch" autofocus placeholder="p.sh. pulë, avokado, mëngjes..." oninput="Ultra.searchLive(this.value)"><span>⌕</span></div><div id="uResults" class="u-results"></div>`);this.searchLive('')},
 searchLive(q){let box=document.querySelector('#uResults');if(!box)return;let a=this.search(q);box.innerHTML=a.slice(0,30).map(r=>`<button onclick="Ultra.close();Ultra.open(Ultra.all().find(x=>x._type==='${r._type}'&&x._i===${r._i}))"><span>${r.icon}</span><div><b>${r.title}</b><small>${r._type==='baby'?r.age:r.cat} · ${r.time}</small></div><i>→</i></button>`).join('')||'<p class="u-empty">Nuk u gjet asnjë recetë.</p>'},
 showSaved(){let ids=this.favs(),a=this.all().filter(r=>ids.includes(`${r._type}:${r._i}`));this.modal(`<div class="u-modal-head"><div><small>KOLEKSIONI YT</small><h2>Të preferuarat</h2></div><button onclick="Ultra.close()">×</button></div><div class="u-results">${a.length?a.map(r=>`<button onclick="Ultra.close();Ultra.open(Ultra.all().find(x=>x._type==='${r._type}'&&x._i===${r._i}))"><span>${r.icon}</span><div><b>${r.title}</b><small>${r._type==='baby'?r.age:r.cat} · ${r.time}</small></div><i>→</i></button>`).join(''):'<p class="u-empty">Ende nuk ke ruajtur receta. Hape një recetë dhe shtype zemrën.</p>'}</div>`)},
 renderSaved(){document.querySelectorAll('[data-fav]').forEach(b=>{b.classList.toggle('on',this.favs().includes(b.dataset.fav))})},
 showPlanner(){let p=this.get(this.keyPlan,{}),days=['Hënë','Martë','Mërkurë','Enjte','Premte','Shtunë','Diel'];this.modal(`<div class="u-modal-head"><div><small>JAVA JOTE</small><h2>Meal Planner</h2></div><button onclick="Ultra.close()">×</button></div><p class="u-sub">Zgjidh nga recetat e Miranda për secilën ditë. Lista e blerjeve krijohet nga plani.</p><div class="planner">${days.map(d=>`<div><b>${d}</b><select onchange="Ultra.plan('${d}',this.value)"><option value="">Zgjidh recetën</option>${this.all().map(r=>`<option value="${r._type}:${r._i}" ${p[d]===`${r._type}:${r._i}`?'selected':''}>${r.title}</option>`).join('')}</select></div>`).join('')}</div><button class="u-primary" onclick="Ultra.buildShop()">Krijo listën e blerjeve</button>`)},
 plan(d,v){let p=this.get(this.keyPlan,{});v?p[d]=v:delete p[d];this.set(this.keyPlan,p)},
 buildShop(){let p=this.get(this.keyPlan,{}),ids=Object.values(p),items=[];ids.forEach(id=>{let [t,i]=id.split(':');let r=this.all().find(x=>x._type===t&&x._i==i);if(r)items.push(...r.ingredients)});this.set(this.keyShop,[...new Set(items)]);this.close();this.showShop()},
 showShop(){let a=this.get(this.keyShop);this.modal(`<div class="u-modal-head"><div><small>MEAL PLANNER</small><h2>Lista e blerjeve</h2></div><button onclick="Ultra.close()">×</button></div><div class="shop-list">${a.length?a.map((x,i)=>`<label><input type="checkbox"><span>${x}</span></label>`).join(''):'<p class="u-empty">Planifiko javën për ta krijuar listën automatikisht.</p>'}</div>`)},
 showHub(){this.modal(`<div class="u-modal-head"><div><small>MIRANDA V8</small><h2>Qendra Miranda</h2></div><button onclick="Ultra.close()">×</button></div><div class="hub-grid"><button onclick="Ultra.close();home()"><span>🍼</span><b>Baby Table</b><small>6–12 muaj</small></button><button onclick="Ultra.close();openDiet()"><span>🥗</span><b>Healthy Table</b><small>Për të rritur</small></button><button onclick="Ultra.close();Ultra.showPlanner()"><span>▦</span><b>Planifiko</b><small>Java jote</small></button><button onclick="Ultra.close();Ultra.showShop()"><span>✓</span><b>Blerjet</b><small>Lista smart</small></button></div>`)},
 modal(html){this.close();let d=document.createElement('div');d.id='uOverlay';d.className='u-overlay';d.innerHTML=`<div class="u-modal">${html}</div>`;d.onclick=e=>{if(e.target===d)this.close()};document.body.appendChild(d);requestAnimationFrame(()=>d.classList.add('show'))},close(){document.querySelector('#uOverlay')?.remove()},
 enhanceDetail(){let copy=document.querySelector('.detail-copy,.diet-detail>div:last-child');if(!copy)return;let title=copy.querySelector('h1')?.textContent;let r=this.all().find(x=>x.title===title);if(!r)return;let bar=document.createElement('div');bar.className='recipe-actions';bar.innerHTML=`<button data-fav="${r._type}:${r._i}" onclick="Ultra.toggleFav('${r._type}',${r._i})">♡ <span>Ruaje</span></button><button onclick="Ultra.cook('${r._type}',${r._i})">▶ <span>Cooking mode</span></button><button onclick="navigator.share?navigator.share({title:'${r.title.replaceAll("'","\\'")}',url:location.href}):Ultra.toast('Linku është gati për shpërndarje')">↗ <span>Shpërndaje</span></button>`;copy.querySelector('h1').after(bar);this.renderSaved()},
 cook(t,i){let r=this.all().find(x=>x._type===t&&x._i===i),n=0;const draw=()=>this.modal(`<div class="cook"><small>COOKING MODE · ${n+1}/${r.steps.length}</small><div class="cook-icon">${r.icon}</div><h2>${r.steps[n]}</h2><div><button ${n===0?'disabled':''} onclick="Ultra.close();Ultra.cookStep('${t}',${i},${n-1})">←</button><button onclick="Ultra.close()">Mbylle</button><button ${n===r.steps.length-1?'disabled':''} onclick="Ultra.close();Ultra.cookStep('${t}',${i},${n+1})">→</button></div></div>`);draw()},cookStep(t,i,n){let r=this.all().find(x=>x._type===t&&x._i===i);this.modal(`<div class="cook"><small>COOKING MODE · ${n+1}/${r.steps.length}</small><div class="cook-icon">${r.icon}</div><h2>${r.steps[n]}</h2><div><button ${n===0?'disabled':''} onclick="Ultra.close();Ultra.cookStep('${t}',${i},${n-1})">←</button><button onclick="Ultra.close()">Mbylle</button><button ${n===r.steps.length-1?'disabled':''} onclick="Ultra.close();Ultra.cookStep('${t}',${i},${n+1})">→</button></div></div>`)},
 nav(){if(document.querySelector('.u-bottom'))return;let n=document.createElement('nav');n.className='u-bottom';n.innerHTML=`<button onclick="Ultra.showHub()"><b>⌂</b><span>Ballina</span></button><button onclick="Ultra.showSearch()"><b>⌕</b><span>Kërko</span></button><button onclick="Ultra.showPlanner()"><b>▦</b><span>Planifiko</span></button><button onclick="Ultra.showShop()"><b>✓</b><span>Lista</span></button><button onclick="Ultra.showSaved()"><b>♡</b><span>Ruajtur</span></button>`;document.body.appendChild(n)}
};
function ultraBoot(){Ultra.nav();setTimeout(()=>Ultra.enhanceDetail(),30)}
new MutationObserver(()=>{clearTimeout(window.__ub);window.__ub=setTimeout(ultraBoot,40)}).observe(document.querySelector('#app'),{childList:true,subtree:false});ultraBoot();