/* ASCEND PREP V12 — functional demo interaction layer */
const demoState={planDone:new Set([0,1]),noteFilter:'Due now',saved:new Set([0,1,2]),dailyTarget:40,examDate:'September 12, 2026'};
function toast(msg){let old=document.querySelector('.v12toast');if(old)old.remove();let t=document.createElement('div');t.className='v12toast';t.textContent=msg;document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),220)},1700)}
function studyPlan(){const items=[['Mon','Retention review','15 min'],['Tue','People · 40 questions','42 min'],['Wed','Process · 30 questions','35 min'],['Thu','Incorrect review · 25 questions','28 min'],['Fri','Mixed timed set · 60 questions','72 min'],['Sat','Smart recall','20 min']];page('Study plan',`<div class="pageTitle"><span class="eyebrow">LEARNING PATH · V12</span><h1>Your adaptive week.</h1><p>Tap a session to mark it complete. Start any session directly.</p></div><div class="planHero"><div>${ring(Math.round(demoState.planDone.size/items.length*100),'WEEK')}</div><div><small>THIS WEEK</small><h2>${demoState.planDone.size} of ${items.length} sessions complete</h2><p>The demo plan now responds to your actions.</p><div class="bar"><i style="width:${demoState.planDone.size/items.length*100}%"></i></div></div></div><div class="v12PlanGrid">${items.map((x,i)=>`<article class="v12PlanCard ${demoState.planDone.has(i)?'done':''}"><div class="v12PlanTop"><span>${x[0]}</span><button onclick="togglePlan(${i})">${demoState.planDone.has(i)?'✓':'○'}</button></div><small>${i<2?'REVIEW':i===2?'PRIORITY':'PLANNED'}</small><h3>${x[1]}</h3><p>${x[2]} · ${i%2?'Adaptive':'Focused'}</p><button class="btn ${i===2?'primary':''}" onclick="practice()">Start session →</button></article>`).join('')}</div>`)}
function togglePlan(i){demoState.planDone.has(i)?demoState.planDone.delete(i):demoState.planDone.add(i);studyPlan();toast(demoState.planDone.has(i)?'Session completed':'Session reopened')}
const demoNotes=[['Change Control','Assess impact before approval or implementation.','Due now','Process'],['Servant Leadership','Facilitate resolution and remove impediments before escalating.','Tomorrow','People'],['Risk Response','Document, analyze and assign an appropriate response.','3 days','Process'],['Stakeholder Engagement','Engage based on influence, impact and current engagement.','Due now','People']];
function notebook(filter=demoState.noteFilter){demoState.noteFilter=filter;let rows=filter==='All'?demoNotes:filter==='Due now'?demoNotes.filter(x=>x[2]==='Due now'):demoNotes.filter(x=>x[3]===filter);page('Notebook',`<div class="pageTitle"><span class="eyebrow">SMART REVIEW · V12</span><h1>Remember what matters.</h1><p>Filters and review actions are interactive in this demo.</p></div><div class="noteFilters">${['Due now','All','Process','People'].map(x=>`<button class="${filter===x?'activePick':''}" onclick="notebook('${x}')">${x}</button>`).join('')}</div><div class="v12NoteGrid">${rows.map((x,i)=>`<article class="noteCard"><div><small>${x[2]} · ${x[3]}</small><h3>${x[0]}</h3><p>${x[1]}</p></div><button class="btn" onclick="toast('Review scheduled')">Review</button></article>`).join('')}</div>`)}
function bookmarks(){const data=['Stakeholder requests a feature outside approved scope.','A team member identifies a new project risk.','The sprint goal is threatened by an external dependency.'];page('Bookmarks',`<div class="pageTitle"><span class="eyebrow">SAVED · V12</span><h1>Questions worth revisiting.</h1><p>Saved items can now be removed or opened.</p></div><div class="v12SavedGrid">${data.map((x,i)=>demoState.saved.has(i)?`<article class="saved"><div><small>${i===0?'PROCESS':'PEOPLE'} · MODERATE</small><h3>${x}</h3><span>Saved for review</span></div><div class="v12Actions"><button class="btn" onclick="practice()">Open</button><button class="btn" onclick="removeBookmark(${i})">Remove</button></div></article>`:'').join('')}</div>`)}
function removeBookmark(i){demoState.saved.delete(i);bookmarks();toast('Bookmark removed')}
function settings(){page('Settings',`<div class="pageTitle"><span class="eyebrow">PREFERENCES · V12</span><h1>Make learning fit you.</h1><p>These demo controls now update state.</p></div><section class="dashCard v12Settings"><div class="settingRow"><div><b>App version</b><span>Ascend Prep V12 · Demo</span></div><b class="versionTag">V12</b></div><div class="settingRow"><div><b>Current exam</b><span>${currentExam}</span></div><button class="btn" onclick="home()">Switch</button></div><div class="settingRow"><div><b>Exam date</b><span>${demoState.examDate}</span></div><button class="btn" onclick="changeExamDate()">Change</button></div><div class="settingRow"><div><b>Daily target</b><span>${demoState.dailyTarget} questions</span></div><button class="btn" onclick="changeTarget()">Adjust</button></div><div class="settingRow"><div><b>Adaptive recommendations</b><span>Prioritize weak and due concepts</span></div><label class="switch"><input type="checkbox" checked onchange="toast(this.checked?'Adaptive recommendations on':'Adaptive recommendations off')"><i></i></label></div><div class="settingRow"><div><b>Daily reminders</b><span>7:00 PM</span></div><label class="switch"><input type="checkbox" checked onchange="toast(this.checked?'Reminder enabled':'Reminder disabled')"><i></i></label></div></section>`)}
function changeTarget(){let n=prompt('Daily question target',demoState.dailyTarget);if(n&&Number(n)>0){demoState.dailyTarget=Math.min(200,Math.round(Number(n)));settings();toast('Daily target updated')}}
function changeExamDate(){let d=prompt('Exam date',demoState.examDate);if(d&&d.trim()){demoState.examDate=d.trim();settings();toast('Exam date updated')}}
function historyPage(){const rows=[['Today','Adaptive','30','83%'],['Yesterday','Timed','60','78%'],['Jul 21','Review','24','88%'],['Jul 20','Custom','40','75%']];page('History',`<div class="pageTitle"><span class="eyebrow">ACTIVITY · V12</span><h1>Your learning record.</h1><p>Tap a session to reopen a demo review.</p></div><div class="historyTable">${rows.map(x=>`<button class="historyRow v12History" onclick="practice()">${x.map(y=>`<span>${y}</span>`).join('')}</button>`).join('')}</div>`)}
function wireV12(){document.querySelectorAll('.difficulty span').forEach(el=>{el.onclick=()=>{document.querySelectorAll('.difficulty span').forEach(x=>x.classList.remove('activePick'));el.classList.add('activePick');toast(el.textContent+' difficulty selected')}});document.querySelectorAll('.checkRow input').forEach(el=>el.onchange=()=>toast(el.checked?'Domain included':'Domain excluded'))}
const _createTest=createTest;createTest=function(){_createTest();wireV12()};
