/* ASCEND PREP V18 — NCLEX-RN adaptive demo engine */
const V16_KEY='ascend_rn_v16';
const v16Default={examDate:'2026-09-12',dailyTarget:40,answers:[],review:[],streak:12,lastStudy:'',domains:{Cardiovascular:{correct:18,total:30,weight:1.25},Pharmacology:{correct:24,total:40,weight:1.2},Endocrine:{correct:18,total:25,weight:1},Respiratory:{correct:23,total:28,weight:1},Fundamentals:{correct:34,total:40,weight:.9}}};
function v16Clone(x){return JSON.parse(JSON.stringify(x))}
function v16Load(){const base=v16Clone(v16Default);try{const saved=JSON.parse(localStorage.getItem(V16_KEY)||'{}');base.examDate=typeof saved.examDate==='string'?saved.examDate:base.examDate;base.dailyTarget=Number.isFinite(saved.dailyTarget)?saved.dailyTarget:base.dailyTarget;base.answers=Array.isArray(saved.answers)?saved.answers:[];base.review=Array.isArray(saved.review)?saved.review:[];base.streak=Number.isFinite(saved.streak)?saved.streak:base.streak;base.lastStudy=typeof saved.lastStudy==='string'?saved.lastStudy:'';if(saved.domains&&typeof saved.domains==='object'){Object.keys(base.domains).forEach(k=>{if(saved.domains[k]&&typeof saved.domains[k]==='object')base.domains[k]=Object.assign({},base.domains[k],saved.domains[k])})}return base}catch(e){return base}}
let rnState=v16Load();
function v16Save(){try{localStorage.setItem(V16_KEY,JSON.stringify(rnState))}catch(e){}}
function v16Pct(d){return d&&d.total?Math.round(d.correct/d.total*100):0}
function v16Readiness(){let ds=Object.values(rnState.domains),weighted=ds.reduce((s,d)=>s+v16Pct(d)*d.weight,0)/ds.reduce((s,d)=>s+d.weight,0);let retention=Math.max(55,92-rnState.review.length*2);return Math.round(weighted*.72+retention*.18+Math.min(100,rnState.answers.length*2)*.10)}
function v16Weak(){return Object.entries(rnState.domains).sort((a,b)=>v16Pct(a[1])-v16Pct(b[1]))[0][0]}
function v16Days(){let t=new Date(rnState.examDate+'T12:00:00'),n=new Date();return Math.max(0,Math.ceil((t-n)/86400000))}
const rnQuestions=[
{id:1601,domain:'Cardiovascular',difficulty:'Moderate',stem:'A client with heart failure receives furosemide. Which finding requires the nurse’s priority follow-up?',options:['Blood pressure 118/72 mm Hg','Potassium 2.9 mEq/L','Urine output 900 mL in 8 hours','Mild thirst after ambulation'],correct:1,logic:'Loop diuretics can cause clinically significant potassium loss. A potassium of 2.9 mEq/L increases dysrhythmia risk and requires prompt follow-up.',why:['This blood pressure is not hypotensive.','Correct: this represents significant hypokalemia.','This urine output is adequate.','Mild thirst is not the priority finding.'],rule:'With loop diuretics, connect potassium loss to cardiac electrical instability.',memory:'Furosemide → K+ falls → rhythm risk.'},
{id:1602,domain:'Pharmacology',difficulty:'Moderate',stem:'The nurse is preparing to administer digoxin. Which assessment finding should cause the nurse to hold the medication and notify the provider?',options:['Apical pulse 54/min','Respiratory rate 18/min','Blood pressure 132/76 mm Hg','Potassium 4.1 mEq/L'],correct:0,logic:'Digoxin can slow atrioventricular conduction. An adult apical pulse below the prescribed safety threshold is a reason to hold the dose and seek further direction.',why:['Correct: bradycardia increases concern for digoxin effect or toxicity.','This respiratory rate is expected.','This blood pressure is acceptable.','This potassium value is within the usual reference range.'],rule:'Assess the apical pulse before digoxin; clinically important bradycardia changes the administration decision.',memory:'Digoxin slows the heart → check apical pulse first.'},
{id:1603,domain:'Endocrine',difficulty:'Hard',stem:'A conscious client with diabetes is diaphoretic, shaky, and confused. Bedside glucose is 48 mg/dL. What should the nurse do first?',options:['Administer 15 g of rapid-acting carbohydrate','Give long-acting insulin','Restrict oral intake','Recheck glucose in 2 hours'],correct:0,logic:'A conscious client with symptomatic hypoglycemia who can swallow should receive rapid-acting carbohydrate immediately, followed by reassessment.',why:['Correct: immediate glucose replacement treats symptomatic hypoglycemia.','Insulin would worsen hypoglycemia.','Restricting intake delays treatment.','Waiting two hours is unsafe.'],rule:'Treat symptomatic hypoglycemia immediately when the client can safely swallow.',memory:'Low + awake + can swallow → fast carbohydrate.'}
];
let rnQIndex=0,rnSelected=null;
function rnV16Dashboard(){currentExam='NCLEX-RN';let r=v16Readiness(),weak=v16Weak(),days=v16Days(),today=rnState.answers.filter(a=>a.day===new Date().toISOString().slice(0,10)).length;page('Overview',`<header class="v16Head"><div><small>ASCEND PREP · NCLEX-RN <b class="v18Badge">V18</b></small><h1>Ready smarter.</h1><p>Your highest-value study move, at a glance.</p></div><button onclick="home()">Switch exam</button></header><section class="v16Command"><div><small>PRIORITY FOCUS · TODAY</small><h2>${weak}</h2><p>Lowest mastery area. One focused adaptive set gives you the highest-value next move.</p><div><button class="btn primary" onclick="rnV16Practice('${weak}')">Start focus set →</button><button class="btn" onclick="rnV16Why()">Why?</button></div></div><div class="v16Ready"><div class="v16ReadyRing" style="--r:${r}%"><strong>${r}%</strong><span>READY</span></div><b>${r>=80?'Exam-ready':r>=65?'On track':'Building'}</b><small>${days}d left</small></div></section><section class="v16Metrics"><article><small>TODAY</small><b>${today}<em> / ${rnState.dailyTarget}</em></b><i><u style="width:${Math.min(100,today/rnState.dailyTarget*100)}%"></u></i></article><article><small>REVIEW</small><b>${rnState.review.length}</b><button onclick="rnV16Review()">Open →</button></article><article><small>HISTORY</small><b>${rnState.answers.length}</b><span>answers</span></article><article><small>EXAM</small><b>${days}<em>d</em></b><button onclick="settings()">Edit →</button></article></section><div class="v16Title"><div><small>MASTERY</small><h2>RN blueprint</h2></div><button onclick="performance()">Analytics</button></div><section class="v16Domains">${Object.entries(rnState.domains).sort((a,b)=>v16Pct(a[1])-v16Pct(b[1])).map(([n,d],i)=>`<button onclick="rnV16Practice('${n}')"><div><i>${String(i+1).padStart(2,'0')}</i><b>${n}</b><span>${d.total} attempts</span></div><strong>${v16Pct(d)}%</strong><em><u style="width:${v16Pct(d)}%"></u></em><q>Practice →</q></button>`).join('')}</section><section class="v16Plan"><div class="v16Title"><div><small>QUICK START</small><h2>Study now</h2></div><button onclick="studyPlan()">Plan</button></div><div class="v16PlanGrid"><button onclick="rnV16Practice('${weak}')"><i>01</i><b>Weak area</b><span>${weak} · 20 Q</span></button><button onclick="rnV16Review()"><i>02</i><b>Smart recall</b><span>${rnState.review.length} due</span></button><button onclick="rnV16Practice('Mixed')"><i>03</i><b>Mixed set</b><span>Adaptive</span></button></div></section>`)}
function rnV16Why(){toast(`${v16Weak()} is prioritized from current mastery and blueprint weight.`)}
function rnV16Practice(domain='Mixed'){let pool=domain==='Mixed'?rnQuestions:rnQuestions.filter(q=>q.domain===domain);if(!pool.length)pool=rnQuestions;rnQIndex=0;rnSelected=null;rnV16Question(pool,domain)}
function rnV16Question(pool,domain){let q=pool[rnQIndex%pool.length];page('QBank',`<div class="v16PracticeTop"><button onclick="rnV16Dashboard()">← Exit</button><div><b>${domain} adaptive set</b><span>Question ${rnQIndex+1}</span></div><em>${q.difficulty}</em></div><section class="v16Question"><div class="v16QMeta"><span>${q.domain}</span><b>NCLEX-RN · V18 · SINGLE BEST ANSWER</b></div><h2>${q.stem}</h2><div class="v16Options">${q.options.map((x,i)=>`<button onclick="rnV16Select(${i},this)"><i>${String.fromCharCode(65+i)}</i><span>${x}</span></button>`).join('')}</div><div class="v16Confidence"><span>Confidence</span><button onclick="toast('Confidence: Low')">Low</button><button onclick="toast('Confidence: Medium')">Medium</button><button onclick="toast('Confidence: High')">High</button></div><button class="btn primary v16Submit" onclick='rnV16Submit(${JSON.stringify(pool).replace(/'/g,"&#39;")},${JSON.stringify(domain)})'>Submit answer</button><div id="v16Explain"></div></section>`)}
function rnV16Select(i,el){rnSelected=i;document.querySelectorAll('.v16Options button').forEach(x=>x.classList.remove('on'));el.classList.add('on')}
function rnV16Submit(pool,domain){if(rnSelected===null){toast('Select an answer first');return}let q=pool[rnQIndex%pool.length],ok=rnSelected===q.correct,d=rnState.domains[q.domain];if(d){d.total++;if(ok)d.correct++}rnState.answers.push({id:q.id,correct:ok,domain:q.domain,day:new Date().toISOString().slice(0,10)});if(!ok&&!rnState.review.some(x=>x.id===q.id))rnState.review.push({id:q.id,domain:q.domain,due:Date.now()});if(ok)rnState.review=rnState.review.filter(x=>x.id!==q.id);v16Save();document.querySelectorAll('.v16Options button').forEach((x,i)=>{x.disabled=true;if(i===q.correct)x.classList.add('correct');else if(i===rnSelected)x.classList.add('wrong')});document.querySelector('.v16Submit').style.display='none';document.querySelector('#v16Explain').innerHTML=`<section class="v16Explain"><div class="${ok?'good':'bad'}"><b>${ok?'Correct':'Incorrect'}</b><span>${q.logic}</span></div><div class="v16ExplainGrid"><article><small>ANSWER LOGIC</small><p>${q.logic}</p></article><article><small>WHY THE OTHERS FAIL</small>${q.why.map((x,i)=>`<p><b>${String.fromCharCode(65+i)}</b> ${x}</p>`).join('')}</article><article><small>KEY RULE</small><p>${q.rule}</p></article><article><small>MEMORY ANCHOR</small><p>${q.memory}</p></article></div><div class="v16Next"><span>Readiness now <b>${v16Readiness()}%</b></span><button class="btn primary" onclick='rnV16Next(${JSON.stringify(pool).replace(/'/g,"&#39;")},${JSON.stringify(domain)})'>Next question →</button></div></section>`}
function rnV16Next(pool,domain){rnQIndex++;rnSelected=null;rnV16Question(pool,domain)}
function rnV16Review(){if(!rnState.review.length){toast('No concepts are due right now');return}let ids=rnState.review.map(x=>x.id),pool=rnQuestions.filter(q=>ids.includes(q.id));if(!pool.length)pool=rnQuestions;rnQIndex=0;rnSelected=null;rnV16Question(pool,'Smart Review')}
const v16OldDashboard=dashboard;dashboard=function(){return currentExam==='NCLEX-RN'?rnV16Dashboard():v16OldDashboard()};
const v16OldSelect=selectExam;selectExam=function(x){currentExam=x;if(x==='NCLEX-RN')return rnV16Dashboard();return v16OldSelect(x)};
